### ISSUE TITLE
Suggestion/Collaboration

### ISSUE THREAD

**Issue by jamielob** [narendrashetty/react-native-styles-shorthand#1]
Hey @narendrashetty.  I was just about to create something very similar to what you've started here.

The API would be:

```
import StyleSheet from 'react-native-styles-shorthand';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    margin: '10 20 30 40'
  },
  welcome: {
    padding: '10 20',
    margin: '100',
  }
});
```

That means that in order to switch over to using this package, all you would need to do if change where you're importing `StyleSheet` from.

**Comment by jamielob** [comment]
Nevermind! Just found this:

https://github.com/torifat/babel-plugin-react-native-css-shorthand

**Comment by narendrashetty** [comment]
@jamielob Good point! Totally makes sense. I'll try and implement it in the next release. Thank you.
